# Generated by Django 4.2.7 on 2023-11-22 15:33

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Role', models.CharField(choices=[('Customer', 'Customer'), ('Health_provider', 'Health_provider')], default='Meeting', max_length=20)),
                ('AppointmentType', models.CharField(choices=[('Check_up', 'Check_up'), ('Consultation', 'Consultation'), ('Mental_health', 'Mental_health'), ('Breastfeeding', 'Breastfeeding'), ('virtual_meetup', 'virtual _meetup')], max_length=20)),
                ('AppointmentStatus', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Scheduled', max_length=20)),
                ('Comment', models.CharField(max_length=500)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('emailadress', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='landlord_profile_pic')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ratings', models.CharField(choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Unsatisfied', 'Unsatisfied ')], max_length=20)),
                ('Response_Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Health_provider',
            fields=[
                ('Health_providerID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('emailadress', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[(' Gynecologist ', ' Gynecologist '), (' Midwives', ' Midwives'), (' Psychologists', ' Psychologists'), ('Nurses:', 'Nurses:'), ('Peer_support', 'SelfPeer_support')], max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='landlord_profile_pic')),
            ],
            options={
                'db_table': 'Health_provider',
            },
        ),
        migrations.CreateModel(
            name='PD_SCREENING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Screening_tool', models.CharField(choices=[('Edinburgh Postnatal Depression Scale', 'Edinburgh Postnatal Depression Scale'), ('Patient Health Questionnaire', 'Patient Health Questionnaire'), ('Postpartum Depression Screening Scale', 'Postpartum Depression Screening Scale'), ('Beck Depression Inventory-II ', 'Beck Depression Inventory-II'), ('Zung Self-Rating Depression Scale ', 'Zung Self-Rating Depression Scale ')], max_length=300)),
                ('Score', models.CharField(choices=[('0_10', '0_10'), ('11_20', '11_20'), ('21_30', '21_30 '), ('31_40', '31_40'), ('41-50', '41-50'), ('Above 50', 'Above 50')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Resource_Locator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResourceType', models.CharField(choices=[('Mental-health videos', 'Mental-health videos'), ('Articles', 'Articles'), ('Treatment Guides', 'Treatment Guides'), ('Resource Directories', 'Resource Directories'), ('User_guides', 'User_guides')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Health_provider', 'Health_provider')], max_length=209)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
